### ISSUE TITLE
Programming newbie Ask Big Brother for help, thank you

### ISSUE THREAD

**Issue by jaylin321** [vk7055/NTS-New-Train-Scheduler#1]
Hello, may I ask this project to create a C# project class in vs. is a form control library? What is the sql server version, my win7 used sql 2008 version, the program was interrupted after compilation, "Failed to find the assembly, the details openclipbord failed

![2YD4Y8X}HC1O4J}Q_J}L~Z7](https://user-images.githubusercontent.com/49814918/56605170-15b59680-6636-11e9-861c-71af83f1781f.png)
![ZXBW{%ZF(6W2CT@JTV5AJ@M](https://user-images.githubusercontent.com/49814918/56605177-19491d80-6636-11e9-9138-2916308f026c.png)

**Comment by vk7055** [comment]
Hello @jaylin321 , repo does not have all the files required in proper directory structure.

Use this link (https://drive.google.com/open?id=0B2_sfbLeyvDHdzZyYktwTkIzVzg) to get the project with proper directory structure. Use Train_Scheduler_2.sln file to launch the project.

Analyse Train_Scheduler_2.csproj file for dependencies if you face issues.

Hope it helps.
